version: '3'

networks:
  monreseau:
    external: false

services:
  web:
    build: .
    container_name: contweb
    volumes:
      - .:/code
      - ./static:/static
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '5000:5000'

  nginx:
    image: 'nginx:1.19-alpine'
    container_name: contnginx
    volumes:
      - ./static:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/media
    depends_on:
      - web
    ports:
      - '80:80'
